main_page/urls.py
from django.conf.urls import url

from . import views

app_name = 'main_page'

urlpatterns = [
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about'),
    url(r'^projects/$', views.projects, name='projects'),
    url(r'^resume.docx/$', views.resume, name='resume'),

]

portfolio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main_page import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name="index"),
    url(r'^main/', include('main_page.urls')),

]

main_page/models.py
from django.db import models

from datetime import datetime

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    msg = models.TextField(max_length=1000)
    date = models.DateTimeField(default=datetime.now)
    sent = models.BooleanField(default=False)

main_page/forms.py
from django.forms import ModelForm

from .models import Message

class MessageForm(ModelForm):
    # msg =
    class Meta:
        model = Message
        fields = ['name', 'email', 'msg']

main_page/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import MessageForm
from .models import Message

# Create your views here.
def index(request):
    return render(request, 'index.html')

def contact(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            m = form.save()
            return HttpResponseRedirect("/")
    else:
        form = MessageForm()
    return render(request, 'contact.html', {'form': form})

def about(request):
    return render(request, 'about.html')

def projects(request):
    return render(request, 'projects.html')

def resume(request):
    with open(os.path.join(MEDIA_DIR, 'rafaelRibeiroResumePortfolio.docx', 'rb')) as doc:
        response = HttpResponse(doc.read())
        response['content_type'] = 'application/docx'
        response['Content-Disposition'] = 'attachment;rafaelRibeiroResumePortfolio.docx'
        return response

main_page/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="content col-8">
  <h1>About This Website:</h1>
  <hr>

  <section class="container msgForm">
    <p>This website was designed and coded by me, all rights reserved.</p>
    <p>The technologies used are HTML5 and CSS3 for the Front-End, as well as
      Python and Django for the Back-End.</p>
    <p>Deployed on Heroku.  </p>
    <!-- <figure>
      <img src="https://s12.favim.com/orig/160406/cat-catstruction-play-on-words-construction-cats-Favim.com-4174852.jpeg" alt="A cat with a safety helmet (Subtitle: Under Construction)">
      <figcaption>Picture from <a href="https://favim.com/image/4174852/">https://favim.com/image/4174852/</a></figcaption>
    </figure> -->
  </section>

</div>

{% endblock %}

main_page/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Rafael Ribeiro</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

  </head>
  <body>

    <nav class="custom-navbar navbar-dark py-4 sticky-top">
      <div class="container">

      <ul class="nav-main nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main_page:projects' %}">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main_page:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main_page:about' %}">About</a>
        </li>
      </ul>
      <ul class="nav-side nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
    </div>
    </nav>

      {% block body_block %}
      {% endblock %}

    <footer class="footer">
      <div class="container">
        <a href="https://github.com/rapacheco"><img src="{% static 'media/github.png' %}" alt="GitHub"></a>
        <a href="https://www.linkedin.com/in/rafael-pacheco-ribeiro/"><img src="{% static 'media/linkedin.png' %}" alt="LinkedIn"></a>
        <a href="https://twitter.com/rapachecobeiro"><img src="{% static 'media/Twitter.png' %}" alt="Twitter"></a>
      </div>
    </footer>

  </body>
</html>

main_page/templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="content col-8">
  <h1>Contact Me</h1>
  <hr>
  <p>Please fill the form below to send a message directly to me. I'll be sure to answer it in no time!</p>

  <form class="container msgForm" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-dark" type="submit" value="Send">
  </form>

</div>

{% endblock %}

main_page/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

  <div class="center">
    <div class="title">
      <h1>Rafael Ribeiro</h1>
      <hr>
      <h2>Computer Programmer</h2>
    </div>
    <img class="photo" src="https://media.licdn.com/dms/image/C5103AQE6IsCCFQ8ofw/profile-displayphoto-shrink_200_200/0?e=1531958400&v=beta&t=D-9TihZjhNfyotXlwx0LtfwN6qQSEX0tGpwO89BWw5c" alt="A photo of myself">
  </div>

  <article class="about-me col-8" style="z-index: -1; margin: auto;">
    <hr style="width: 80%;">
    <p>Absolutely passionate about programming, and always eager to learn new
      things and to improve myself daily. Quick learner and detail-oriented,
      able to work well in teams and to communicate clearly. I am currently
      enrolled in the Computer Programming & Analysis Program at Seneca College,
      where I'm learning and mastering a range of programming languages,
      frameworks, and technologies like C, C++, HTML5, CSS, Javascript, JQuery,
      Bootstrap, Node.js, Express.js, MongoDB, PostgreSQL, and Oracle SQL. In
      my free time, I like to play around with Python, sometimes developing
      simple games with Pygame, and some other times developing web apps with
      Django. Currently looking for a co-op position for the Fall term, where I
      hope to be able to contribute to the success of the Company while
      continuing to improve myself.</p>
    <p>Please visit my <a href="https://github.com/rapacheco">Github</a> page to
      have a look at some side projects of mine, and also feel free to visit my
      <a href="https://www.linkedin.com/in/rafael-pacheco-ribeiro/">LinkedIn</a>
      page. Lastly, you can download a copy of my current Resume
      <a href="{% url 'main_page:resume' %}">here</a>.</p>
      <a href="https://twitter.com/rapachecobeiro">hello</a>
  </article>

  <article class="content col-8" style="margin: auto;">
    <h2>Skills</h2>
    <!-- <hr> -->
    <!-- <p>These are the technologies I am most familiarized about:</p> -->
    <div class="table-responsive-md">
      <table class="skills table">
        <tr>
          <td><img src="{% static 'media/python.png' %}" alt="Python"></td>
          <td><img src="{% static 'media/django.png' %}" alt="Django"></td>
          <td><img src="{% static 'media/js.png' %}" alt="JavaScript"></td>
        </tr>
        <tr>
          <td><img src="{% static 'media/html.png' %}" alt="HTML5"></td>
          <td><img src="{% static 'media/css.png' %}" alt="CSS"></td>
          <td><img src="{% static 'media/c.jpg' %}" alt="C"></td>
        </tr>
      </table>
    </div>
  </article>


{% endblock %}

main_page/templates/projects.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="content col-8">
  <h1>Projects Portfolio:</h1>
  <hr>
  <!-- <p>Please fill the form below to send a message directly to me. I'll be sure to answer it in no time!</p> -->

  <section class="container msgForm">
    <h4>Sorry, this page is still</h4>
    <figure>
      <img src="https://s12.favim.com/orig/160406/cat-catstruction-play-on-words-construction-cats-Favim.com-4174852.jpeg" alt="A cat with a safety helmet (Subtitle: Under Construction)">
      <figcaption>Picture from <a href="https://favim.com/image/4174852/">https://favim.com/image/4174852/</a></figcaption>
    </figure>
  </section>

</div>

{% endblock %}